spring.application.name=mcp-server
#mcp utilise 3 prtocole sse pour cree un servvices a distance protocle unidertionne
#http le clinet connect vers le serures mcp et le serveur mcp envoie les reponses to client
#Stramble il fait d'un manier berdectionnelle
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.name=mcp-rh
server.port=8989
